cmake_minimum_required(VERSION 4.0)
project(editor)

set(BUILD_SHARED_LIBS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_COLOR_DIAGNOSTICS ON)
set(CMAKE_BUILD_WITH_INSTALL_RPATH OFF)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CGLM_STATIC ON)

find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
	set(CMAKE_C_COMPILER_LAUNCHER "ccache")
	set(CMAKE_CXX_COMPILER_LAUNCHER "ccache")
endif()

set(CLANGD_COMPLETION_HEADER_INSERTION Never)
set(CLANGD_DIAGNOSTICS_UNUSED_INCLUDES None)
set(CLANGD_COMPILE_COMMANDS_FILE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/clangd.in ${CMAKE_CURRENT_SOURCE_DIR}/.clangd @ONLY)

include(GNUInstallDirs)
include(cmake/TreeSitterParsers.cmake)

add_subdirectory(vendor/glfw)
add_subdirectory(vendor/harfbuzz)
add_subdirectory(vendor/glad)
add_subdirectory(vendor/cglm)
add_subdirectory(vendor/cgltf)
add_subdirectory(vendor/stb)
add_subdirectory(vendor/lua)
add_subdirectory(vendor/libuv)
add_subdirectory(vendor/tree-sitter)
add_tree_sitter_parser(vendor/tree-sitter-parsers/tree-sitter-c)
add_tree_sitter_parser(vendor/tree-sitter-parsers/tree-sitter-lua)

enable_testing()
include(cmake/UnitTestHelper.cmake)

add_subdirectory(engine)
add_subdirectory(projects/text-editor)
add_subdirectory(projects/model-viewer)
